### PR TITLE
Custom file system model simplify

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
This fixes the described problem with

```
A-
  -B-
     -C-
```

where A is already checked and the user checks C.  It does not fix the reverse problem, where C is already checked and the user checks A.  I need a bit more time to figure out what's happening in this file before I'll submit a fix for that.

**Comment by shinnok** [comment]
This is not just a code split right? If so we need to be really careful touching it and test it thoroughly since that's a very tricky piece, in part due to the limitations set by the API. Let me know when I should look over the changes.

**Comment by gperciva** [comment]
By "code split", you mean "refactoring" ?  Rearranging the code to be easier to understand?  As stated in the comments, the first 4/5 commits do not change any program behavior (so those are merely refactoring).  The last commit changes program behaviour.

I'd be happy to resubmit only the refactoring code as a separate PR.  Then once that's accepted, we can look at the bug fixes for this code separately.

**Comment by gperciva** [comment]
I'll re-open this once #91 is merged.

**Pull request closed without merging**
