### PR TITLE
Customfilesystemmodel test

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
First draft of a unit test for CustomFileSystemModel.  The test scenarios are quite modest right now; if/when the basic framework is accepted, I'll populate it with a few more cases, then resume work on CustomFileSystemModel.

**Comment by shinnok** [comment]
I think this basic test will suffice. Here's how I tested with a known failure case:

> $cat scenario-05.txt 
> \# Grandparent update on grandson checked
> actions:
> + dir-1
> + dir-1/dir-2/dir-3
> 
> results:
> 1 dir-1/dir-2
> 2 dir-1/dir-2/dir-3
> 1 dir-1/dir-2/file-5.txt
> 1 dir-1/dir-2/file-6.txt
> 1 dir-1
> 0 dir-1/file-3.txt
> 0 dir-1/file-4.txt
> 0 file-1.txt
> 0 file-2.txt
> 
>$./testCFSM.app/Contents/MacOS/testCFSM 
> \--
> Test failed!  Desired result:
> 1 dir-1
>   /Users/shinnok/Work/tarsnap/tarsnap-gui/tests/customfilesystemmodel/dirs
> 2	dir-1
> 1		dir-2
> 2			dir-3
> 1			file-5.txt
> 1			file-6.txt
> 1		file-3.txt
> 1		file-4.txt
> 0	file-1.txt
> 0	file-2.txt
> --1 error(s) detected!

I'll merge it once we have a complete test suite. Thanks!

**Comment by gperciva** [comment]
Do you want a complete test suite, including failing tests?  Because I already know of two cases where the current CustomFileSystemModel fails.  I was only going to add those tests once I'd fixed the code, but I could go ahead and add the tests now if you'd prefer.

**Comment by shinnok** [comment]
Yeah, it wouldn't hurt to get what we both found out so far in sync.

**Comment by gperciva** [comment]
Updated with more tests, and slightly modified the "Test failed" output to include the filename.

While constructing these tests, I discovered that one of my "problem cases" is actually a problem with the display, not the underlying model.  That's great, because it shows that testing the model independently of the `emit` commands is a good idea.  :)   I'll tackle that problem once these tests are all passing.

Incidentally, I saw that you used a `dir-3` in your proposed test.  I reworked it so that it would fail in the same way, without using `dir-3`.  Do you think we need another level of dirs?  If so, I'll go ahead and add it, but right now I don't think we need one.

**Comment by gperciva** [comment]
I just thought of how to test the `emit` data as well, so don't pull this yet.

**Comment by gperciva** [comment]
Updated to check both the internal model data, and the emitted data.  The test cases now show all bugs which I'm aware of.

**Comment by shinnok** [comment]
I only checked this branch, did not pull #93, and I'm a bit confused about the output of test case 8:
```

./testCFSM.app/Contents/MacOS/testCFSM 8
--
Test failed: scenario-08.txt
Model emitted state does not match desired state.  Emitted data:
1	dir-1/file-3.txt
1	dir-1/dir-2
1	dir-1/file-4.txt
2	dir-1
--

1 error(s) detected!

```

Why does it fail? The output matches the rules in scenario-08.txt apart from the grandchildren 5,6 which I'd assume they won't update unless the directory is loaded for display.

**Comment by gperciva** [comment]
There are two different things that are being tested (and I think this clarifies your question  about "actual usage" in https://github.com/Tarsnap/tarsnap-gui/pull/93#issuecomment-230837093):
- after all the actions, what are the contents of the model?  In other words, what does `data()` return for each item?
- after all the actions, what did all the `emit dataChanged()` tell us?  (I think you call this "loaded for display"

The test code first checks the model contents.  If those are ok, then it checks what all the `emit dataChanged` told us (it kept track as the scenario was running).

`customfilesystemmodel.cpp` should satisfy both of these requirements.  PR #94 (this one) sets up tests for these, and PR #93 changes the file so that it succeeds all the tests.

**Comment by gperciva** [comment]
As for:
> Why does it fail? The output matches the rules in scenario-08.txt apart from the grandchildren 5,6 which I'd assume they won't update unless the directory is loaded for display.

In current master, grandchildren are not updated.  If you have their directory expanded, and click on the grandfather, the grandchildren are left unselected unless you hover your mouse over the grandchildren.  This is not an ideal case, and is fixed in #93.

But more than anything else, we should not be testing (or discussing) the functionality by saying "open the application, click on this, hover the mouse there, etc".  Let's make sure we have a reliable test suite that we understand (please ask me to comment anything that's unclear!), so that we can make reliable software.

**Comment by gperciva** [comment]
It would be nice if we could agree on the test framework.  I've updated it here; is there anything that should change?

**Comment by gperciva** [comment]
Updated with another nasty corner case.

**Pull request merged**
