### PR TITLE
Version 1.0.x

### PR DESCRIPTION
**Pull request by SoloBSD**

### CODE REVIEW

**Comment by gperciva** [comment]
What's the intent behind this PR?  As far as I know, the `version-1.0.x` branch doesn't contain anything which isn't already in `master`.  Did I miss something?

**Comment by SoloBSD** [comment]
Sorry, I wanted to add Linux Mint 19.3 to the Debian based distros
supported. I didn't know how to do it. So I erased what I had added there
in the PR.

**Comment by gperciva** [comment]
Ah, so adding
```
* Linux Mint 19.3 Tricia
```

to the list of tested distros?  I can add that easily, thanks for testing!

**Comment by gperciva** [comment]
I've added this to the `INSTALL` document, thanks!

**Pull request closed without merging**
