### PR TITLE
Setup: remove "Machine key?", edit "Register..."

### PR DESCRIPTION
**Pull request by gperciva**
Just like we removed the "should the GUI search for the CLI apps?" question
page, this removes the "are you using Tarsnap already?" question page.
Instead, there is a single "Register with server" page.

- if tarsnap-gui finds any existing keys, the "use existing keys" option is
  automatically selected.
- if not, the "create new keys" option is selected.

The user can switch between these options while remaining on the "Register
with server" page.

### CODE REVIEW

**Comment by gperciva** [comment]
Right now this is an "experimental" PR; if you accept the general principle (i.e. the images below, and the logic of the program flow), I'll clean up the code.

gui-new-key

gui-existing-key

**Comment by shinnok** [comment]
Hmm, I'm a bit inclined towards having the simple question and then showing up the relevant page, instead of having a complex looking all encompassing page like this. I want the wizard to slowly teach the user one thing or two about Tarsnap instead of fast-tracking through the setup, especially now that we have no documentation, few tooltips and no help inside the app.

**Comment by gperciva** [comment]
I'll revisit this once other setup-related PRs are merged.

**Comment by gperciva** [comment]
@shinnok wrote:
> I want the wizard to slowly teach the user one thing or two about Tarsnap instead of fast-tracking through the setup

Hmm, that's actually the same reason why I want to combine the "Do you already have a keyfile?" page and the "register with server" page -- I think it's better for user education!  There's 3 basic things that the setup wizard does:

  1. make sure the user has the CLI tools.  (and direct them to tarsnap.com if they don't)
  2. make sure the user can connect to the Tarsnap server.
  3. warn the user to not lose their keyfile.

I've simplified the text a bit, rewritten the code to fit onto current master (or rather, master + #111 and #110).  Looking at these screenshots, I think I need to do a better job on the whitespace -- it's too crowded in the middle of the page, with lots of space on the top and bottom that's wasted.  I'll take a look at the Qt Layout docs and see what I can do.  But it would be nice if you could take a look at this and give any general comments.  :)

(oh, just noticed: if the user clicks on the same button twice, it gets de-selected.  I need to figure out how to make QPushButtons function as a "choice".  Unfortunately QButtonGroup breaks keyboard navigation -- I can't move through different buttons within the group.  Neither tab nor arrows work.)

create
existing

**Pull request merged**
