### PR TITLE
Rename TextLabel to ElidedLabel

### PR DESCRIPTION
**Pull request by gperciva**
The new name gives a better explanation of what the class does.

### CODE REVIEW

**Comment by shinnok** [comment]
You sure the documentation/header is not enough? besides it also adds click handling along with eliding. I think of it as a super QLabel, with added functionality that should be in QLabel anyway (long story here, even have a Qt issue/e-mail for it), I have it in every project I did for years, so for me it's a de facto.

I could do without the extra 6 chars appended, which will increase code width, with minimal gain in clarity.

**Comment by gperciva** [comment]
I considered calling it `ElidedClickableTextLabel`, but thought you'd object to that name.

Yes, the doxygen comments help, but I still think that `TextLabel` gives the wrong impression.  I also asked a friend of mine (one of the leading programmers at a Vancouver game company), and he said "there's no way that should be called `TextLabel`.  Maybe @cperciva will chime in?

**Comment by cperciva** [comment]
So, I don't know what this code does, but "TextLabel" seems like a rather vague name.  C++ is pretty verbose anyway, so I'd lean towards having a more informative name; whether "ElidedTextLabel" is the right one, I don't know.

**Comment by shinnok** [comment]
`ElidedClickableTextLabel` definitely not. This is not Java code. How about `ElidedLabel`, this is after all based on QLabel with added elide support, there isn't anything special nor confusing about it.

**Comment by gperciva** [comment]
I'm not as fond of `ElidedLabel`, but ok, I've updated the PR to use that.

**Pull request merged**
