### PR TITLE
TextLabel comments

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
Question: what is intended by these lines?

```
void TextLabel::mouseReleaseEvent(QMouseEvent *event)
{
    if(event->buttons() ^ Qt::LeftButton)
        emit clicked();
```
and

```
void TextLabel::mouseDoubleClickEvent(QMouseEvent *event)
{
    if(event->buttons() & Qt::LeftButton)
        emit doubleClicked();
```

The result appears to be:
- I can emit `clicked` with my left or middle mouse buttons, but not the right button.
- I can emit a `doubleClicked` with only my left mouse button.

Is that desired; if so, why?  I wonder if we could use

    (event->buttons() == Qt::LeftButton)

instead (if that's what is desired), since it's much more readable.

**Comment by shinnok** [comment]
The mouse event handlers make the TextLabel clickable, mouseReleaseEvent is used in a couple of places, while mouseDoubleClickEvent is not yet used.

The weirdness of the bit logic is better explained here:
http://doc.qt.io/qt-5.6/qmouseevent.html#buttons

**Comment by gperciva** [comment]
Can we remove `mouseDoubleClickEvent`, then?  If you want to keep it, then please let me know why you want it to handle mouse buttons differently than single clicks?  Otherwise it's hard to write a comment to explain why one uses `^` and the other uses `&`.

**Comment by gperciva** [comment]
I removed the Doxyfile; I'll submit that later in a separate PR.  (unfortunately I can't change this PR to use a different branch, otherwise I'd rename the branch)

**Comment by shinnok** [comment]
Sure, you can remove mouseDoubleClickEvent.

**Comment by gperciva** [comment]
Ok, I've removed mouseDoubleClickEvent, but I'm still not fond of:
```
    if(event->buttons() ^ Qt::LeftButton)
        emit clicked();
```

What is intended by the `if` statement?  The above code seems to behave as follows:
- if there is a single left-click, it emits `clicked`.
- if there is a single middle-click, it emits `clicked`.
- if there is a single right-click, the `mouseReleaseEvent` is not called (a context menu appears instead).
- if left and middle buttons are clicked, it emits `clicked`.
- if the left and middle buttons are pressed down, then the middle button is released, it does **not** emit.  
  (^ is this really desired?  seems weird when a single middle-click works!)
- if the left and middle buttons are pressed down, then the left button is released, it **does** emit `clicked`.

Is this the intended behaviour?  If so, why?

I think the behaviour would be easier for both users and programmers if we simply responded to a left-click:
```
    if(event->button() == Qt::LeftButton)
        emit clicked();
```

Dead-simple, no comment needed, and none of the weird inclusion/exclusion that the Qt docs discuss for `->buttons()`:

> For mouse move events, this is all buttons that are pressed down. For mouse press and double click events this includes the button that caused the event. For mouse release events this excludes the button that caused the event.

Speaking from personal experience, it's really weird when trying to debug/understand `^` and seeing `->buttons()` producing an enum of `0` (because my single-clicks were excluded).

**Comment by gperciva** [comment]
Updated PR, including making TextLabel only respond to left-button clicks.

**Comment by gperciva** [comment]
Programming changes have been moved to #71.  This PR is now only comments.

**Comment by gperciva** [comment]
Updated PR to include doxygen config file.

**Pull request merged**
