### PR TITLE
Display already-selected urls in the File Browser

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
Oops, this adds everything again.  Wait a moment, fix coming soon.

**Comment by gperciva** [comment]
Uploaded a new (working) version.

**Comment by shinnok** [comment]
As I see it, this changes the functionality from a add items to the list to a select items for the list. Is this correct? And every new selection clears the Backup list?

**Comment by gperciva** [comment]
Yes, that is correct.  Sorry, I should have been more explicit about that, since it's a non-trivial change of functionality!

I think it's still worth it, and since the file browser loads the existing selection.  But I'm going to double-check that it works as expected.  :)

**Comment by gperciva** [comment]
ok, potential problem: if I open the file browser, then drag a folder into the main area, then click "use selected" (in the file browser), then that latest folder is removed from the list.

I can definitely fix this, though.  Give me a few minutes.

**Comment by gperciva** [comment]
(Summary of what this is trying to fix, since I temporarily lost track of it)

In the original system, with regards to adding files/folders in the File Browser, a user might:
- use the File Browser to add a directory.
- open up the File Browser, notice that their directory is not selected, then select it again.
- receive a warning that adding it twice isn't necessary.

That works ok, but I'm trying to avoid a user making that problem in the first place.

**First attempt**: display the list of already-selected files in the File Browser as "already selected".
**Problem**: there's a synchronization issue between the main window and the File Browser.  Namely, if somebody drags&drops a new folder into the main window while the File Browser is open, that selection isn't added to the File Browser, so when the user clicks "Use selected" in the File Browser", it will lose the dragged&dropped new folder.

**Comment by shinnok** [comment]
Take a look at branch https://github.com/Tarsnap/tarsnap-gui/tree/gperciva-file-browser-already-selected. It fixes the sync issue for item drops in the Backup list.

**Comment by gperciva** [comment]
Nice!  I've updated this PR with a slight edit of the text in the warning box to make it easier to scan quickly.

**Pull request merged**
