### PR TITLE
main: use small logo

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
This is an experimental PR.  Before and after of the main window:

before:
gui-logo-large

after:
gui-logo-small

**Comment by gperciva** [comment]
Note that in addition to using less horizontal space, the new (smaller) logo doesn't need extra vertical space.

**Comment by gperciva** [comment]
Here's two screenshots from virtualbox and ubuntu:

When I first load tarsnap-gui, it has overlap:
gui-too-big

If I drag the window around a bit, it resizes like this, going off the edge of the screen:
gui-too-big-2

**Comment by shinnok** [comment]
Take a look at commit bcacac94b5b42287a8b154c50a08fdae9c3ab672. It features the dynamic logo. :-)

Now the main window can go as low as approx. 430x400:

screen shot 2016-05-09 at 2 44 48 pm
screen shot 2016-05-09 at 2 45 19 pm

**Comment by gperciva** [comment]
Thanks!  Do you really like having the logo being so much higher than the tabs, though?  It looks a bit weird, especially with the small logo -- it seems to be "looming over" the tabs.

**Comment by shinnok** [comment]
Hmm, I guess I could make them even, though I will have to adjust both elements, increase height on the tab button a bit and decrease for the logos.

**Comment by gperciva** [comment]
I'd like to put the idea of always using the small icon forward again.  I've updated this PR.  I think this looks fine:

gui-small-logo

I'm not totally certain why we have a logo in the main window, anyway... firefox and chrome only display their logo in the window title, not inside the main window itself.  I certainly don't think the tabs need to be higher!

**Comment by shinnok** [comment]
How about we sit on the current changes for a release and then come back to this with reconsideration? I like having the full logo in the application, it makes it a bit less utilitarian, plus that the original issue was fixed.

**Comment by shinnok** [comment]
Do you need this PR to stay opened?

**Comment by gperciva** [comment]
I thought you wanted to wait a bit before coming back to it?  Why not use github to remind us about this PR?

**Comment by shinnok** [comment]
I don't think we need the PR to remember about it. If the icon only is indeed something highly desired I'm sure it will come back to us, especially now that it reverts to that if the width is bellow the threshold for displaying the full size logo.

**Comment by gperciva** [comment]
... ok, I have written down a reminder on a piece of paper to re-open this PR later.

**Comment by gperciva** [comment]
Fixed by @shinnok in master.

**Pull request closed without merging**
